os: osx
language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install 'setuptools>=18.5'
  - pip install .
# command to run tests
script: nosetests