language: python
matrix:
    include:
#        - os: osx
#          language: generic
#          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py27
install:
  - bash .travis/install.sh

script:
  - bash .travis/test.sh
